# Занятие 2.
__1. Задачи машинного обучения__
    * Определение
    * Виды машинного обучения
    * Признаки
__2. Демонстрация возможностей библиотеки Pandas__

__3. Алгоритмы обучения__
    * Деревья решений
    * Алгоритм k ближайших соседей
__4. Методы валидации данных__

In [3]:
# Firstly import all required packages
# enable interactive mode of matplotlib
%matplotlib notebook

# import cv2  # python OpenCV
import os  # 
import numpy as np  # lib for arrays
import datetime
import glob
import pandas as pd

import math as mh  # math package

import matplotlib as mpl  
import matplotlib.pyplot as plt  # namespace for plotting
mpl.rcParams['figure.figsize'] = (14,10)  # change default value of plot size

# matplotlib based package for pretty visualization
import seaborn as sns

import time
import pickle  # package for dump & load data
import warnings

## Задачи машинного обучения

__Искусственный интеллект__ - это область информатики, которая занимается разработкой интеллектуальных компьютерных систем, то есть систем, обладающих возможностями, которые мы традиционно связываем с человеческим разумом — понимание языка, обучение, способность рассуждать, решать проблемы и т. д.

<img src="AI.jpg"/>

Определение машинного обучения (T. Mitchell "Machine learning", 1997): "говорят, что компьютерная программа обучается при решении какой-то задачи из класса T, если ее производительность, согласно метрике P, улучшается при накоплении опыта E".

Под опытом E, как правило, понимаются данные, и в зависимости от этого алгоритмы машинного обучения могут быть поделены на тех, что обучаются с учителем и без учителя (supervised & unsupervised learning). 

В задачах обучения без учителя имеется выборка, состоящая из объектов, описываемых набором признаков. В задачах обучения с учителем вдобавок к этому для каждого объекта некоторой выборки, называемой обучающей, известен целевой признак – по сути это то, что хотелось бы прогнозировать для прочих объектов, не из обучающей выборки.

Далее в разных сценариях под T, P, и E подразумеваются совершенно разные вещи. Среди самых популярных задач T в машинном обучении ("Deep Learning", Ian Goodfellow, Yoshua Bengio, Aaron Courville, 2016):

* Классификация - отнесение объекта к одной из $k$ категорий. Задача классификации по сути решается формированием функции $f:R^n→ {1, . . . , k}$. Когда $y = f(x)$, модель устанавливает соответствие между входными данными, описываемыми через вектор $x$ к классу с числовым представлением $y$. Существуют другие варианты задачи классфикации, например, когда в качестве результата функции $f$ получается вектор вероятностей принадлжености к каждому классу (http://cs231n.stanford.edu/). Примером задач классификации является распознавание объектов, когда входными данными является изображение (представленное как правило набором пикселей определенной яркости), а выходными данными - числовой код, идентифицирующий объект на изображении. Современными задачи распознавания объектов наилучшим образом решаются с применением глубокого обучения (Krizhevsky et al., 2012; Ioﬀe and Szegedy, 2015). 

* Классификация с пропущенными данными - задача классификации, когда во входном векторе $x$ представлен не полностью. Для решения задачи алгоритм определяется одной функцией, при которой входному вектору сопоставляется вектор с категориальными данными на выходе. Когда часть входных данных пропущена, вместо одной функции сопоставления обучающийся алгоритм должен обучиться некоторому набору функций. Каждая из этих функций сопоставляется с различным представлением входного вектора $x$ с учетом пропущенных данных. Задачи подобного рода часто встречаются в задачах определения медицинского диагноза, потому что многие типы медицинских тестов являются дорогостоящими или инвазивными. Единственным способом определения такого большого набора функций является обучение вероятностного распределения относительно всех значимых переменных, а затем решая задачу классификации с помощью частных распределений относительно пропущенных данных. Например, в случае, когда входными данными являются $n$ параметров, мы можем получить все $2^n$ различных функций классификации, необходимых для каждого возможного набора из пропущенных данных, но обучающемуся алгоритму необходимо обучаться только одной функции совместной плотности вероятности. 

* Регрессия - прогнозирование количественного признака объекта на основании прочих его признаков. Для решения этой задачи обученный алгоритм представляет из себя функцию $f:R^n→ R$. Задачи регрессии очень близка к задаче классификации, за исключением представления выходных данных. Примерами задачи регрессии является задача определения страховых выплат, формирования цен, биржевого трейдинга, кредитного скоринга - решения о выдаче/невыдаче кредита.

* Транскрипция - в задачах такого типа системе машинного обучения предлагается проанализировать неструктурированное представление некоторых данных и преобразовать его и в дискретную текстовую форму. Примеры: программа распознавания текста, где на вход поступает изображение текста, а на выходе должен быть набор строковых символов; Google Streer View, вход - изображения улиц, на выходе - названия улиц и номера домов; системы распознавания речи (Amazon Alexa, Yandex Alisa, и др.).

* Машинный перевод - 

* кластеризация – разбиение множества объектов на группы на основании признаков этих объектов так, чтобы внутри групп объекты были похожи между собой, а вне одной группы – менее похожи
* детекция аномалий – поиск объектов, "сильно непохожих" на все остальные в выборке либо на какую-то группу объектов
* и много других, более специфичных. Хороший обзор дан в 5 главе книги 

Denoising: In this type of task, the machine learning algorithm is given as input a corrupted example $\widetilde{x} ∈ R^n$ obtained by an unknown corruption process from a _clean example_ $x ∈ R^n$. The learner must predict the clean example
$x$ from its corrupted version $\widetilde{x}$, or more generally predict the conditional probability distribution $p(x |\widetilde{x})$.

## Демонстрация возможностей библиотеки Pandas

**[Pandas](http://pandas.pydata.org)** - библиотека для анализа данных на языке Python с открытым исходным кодом.

Основными структуры данных в Pandas: классы `Series` и `DataFrame`. 

`Series` - одномерный индексированный массив данных некоторого фиксированного типа. 

`DataFrame` - это двухмерная структура данных, представляющая собой таблицу, каждый столбец которой содержит данные одного типа. Можно представлять её как таблицу или словарь объектов типа `Series`. Структура `DataFrame` отлично подходит для представления реальных данных: строки соответствуют признаковым описаниям отдельных объектов, а столбцы соответствуют признакам.

Библиотека `Pandas` предоставляет широкие возможности по считыванию и обработке табличных данных, хранящихся в популярных форматах `.csv`, `.tsv`, `.xlsx`.

### Series

In [6]:
# Create Series object
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    0.321283
b   -0.266141
c    0.617530
d   -1.694410
e    2.227247
dtype: float64

In [9]:
print(s.index)  # get indexes from s

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [75]:
# series object can be create from dict, keys will be indexes
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
pd.Series(d)

a    1
b    2
c    3
d    4
dtype: int64

In [20]:
# it is possible to create Series object with specific indexes, missing keys will be filled by NaN
pd.Series(d, index=['b', 'c', 'd', 'a'])

b    2.0
c    NaN
d    NaN
a    1.0
dtype: float64

In [53]:
# it is possible to create Series object from scalar value
pd.Series(3., index=['a', 'b', 'c', 'd', 'e'])

a    3.0
b    3.0
c    3.0
d    3.0
e    3.0
dtype: float64

In [57]:
# datatype of Series values 
print(s.dtype)

float64

In [49]:
# Series objects supports indexing, slicing and some common for Numpy lib operations
print('Indexing:\n', s[0], end='\n\n')  # indexing
print('Slicing:\n',  s[0: 3], end='\n\n') # slicing
print('Slicing by condition:\n', s[s > s.median()], end='\n\n') # slicing by condition
print('Numpy operations:\n', np.exp(s) * s, end='\n\n')

Indexing:
 0.32128272118004014

Slicing:
 a    0.321283
b   -0.266141
c    0.617530
dtype: float64

Slicing by condition:
 c    0.617530
e    2.227247
dtype: float64

Numpy operations:
 a     0.443015
b    -0.203952
c     1.145111
d    -0.311276
e    20.656149
dtype: float64

In [65]:
# convert values to numpy array
arr_np = np.array(s)
arr_np

array([ 0.32128272, -0.26614055,  0.61752977, -1.69441045,  2.22724683])

In [66]:
# access to elements of Series by key
s['a']

0.32128272118004014

In [70]:
# exception raised when access to non existing key
s['z']

KeyError: 'z'

In [90]:
# to avoid exception we can use method get
print(s.get('a', 10))  # 10 is return if key is not exist
print(s.get('z', 10)) 
print(s.get('z'))      # None is return if key is not exist and default value is not declare

0.32128272118004014
10
None

In [69]:
# we can check existing of specific key in Series instance
print('a' in s, 
      'z' in s)

True False

In [78]:
# the result of an operation between unaligned Series will have the union of the indexes involved
s[1:] + s[:-1]

a         NaN
b   -0.532281
c    1.235060
d   -3.388821
e         NaN
dtype: float64

In [84]:
# assign Name attribute to Series
s1 = pd.Series(np.random.randn(5), name='Series_name')
print(s1)

0   -0.319753
1   -0.495703
2   -0.975963
3   -0.999594
4    1.041677
Name: Series_name, dtype: float64
0   -0.319753
1   -0.495703
2   -0.975963
3   -0.999594
4    1.041677
Name: Series_name, dtype: float64

In [86]:
# we can rename Series - by default it return a copy of Series
s1 = s1.rename('aa')
print(s1)

0   -0.319753
1   -0.495703
2   -0.975963
3   -0.999594
4    1.041677
Name: aa, dtype: float64

In [88]:
# but we can do it in-place
s1.rename('bb', inplace=True)
print(s1)

0   -0.319753
1   -0.495703
2   -0.975963
3   -0.999594
4    1.041677
Name: bb, dtype: float64

### DataFrame

`DataFrame` - основной и наиболее популярный в использовании формат данных в `Pandas`.
При создании объекта `DataFrame` входные данные могут представлены в следующем виде:
* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

В зависимости от типа входных данных при создании, дополнительно можно указать index (row labels) и columns (column labels). Если при создании передается массив индексов или столбцов, то гарантируется, что при создании объект в качестве индексов/столбцов гарантированно будет иметь их. В соответствии с этим, dict of Series и index покроет полностью все возможные индексы при создании.

In [92]:
# dict of Series
d = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

In [94]:
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [97]:
# in Jupyter you can see dataframe by build-in solutions
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [96]:
# we can drop when creating dataframe some indixes by sending specific indixes
pd.DataFrame(d, index=['d', 'b', 'a'])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [98]:
# non existing values will be created with None
pd.DataFrame(d, index=['d', 'b', 'a'], columns=['two', 'three'])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [99]:
# we can get index and column names
print(df.index)
print(df.columns)

Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['one', 'two'], dtype='object')

In [103]:
# create dataframe from list of dicts
data2 = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [104]:
pd.DataFrame(data2)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [107]:
pd.DataFrame(data2, index=['row1', 'row2'])

      a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [110]:
pd.DataFrame(data2, columns=['a', 'b', 'z'])

   a   b   z
0  1   2 NaN
1  5  10 NaN

In [115]:
df['three'] = df['one'] + df['two']
df

   one  two  three
a  1.0  1.0    2.0
b  2.0  2.0    4.0
c  3.0  3.0    6.0
d  NaN  4.0    NaN

In [119]:
df.fillna(0, inplace=True)
df

   one  two  three
a  1.0  1.0    2.0
b  2.0  2.0    4.0
c  3.0  3.0    6.0
d  0.0  4.0    0.0

In [120]:
df

   one  two  three
a  1.0  1.0    2.0
b  2.0  2.0    4.0
c  3.0  3.0    6.0
d  0.0  4.0    0.0

In [128]:
# create column as condition of another column
df['flag'] = df['one'] > 2
df

   one  two  three   flag
a  1.0  1.0    2.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    6.0   True
d  0.0  4.0    0.0  False

In [129]:
# we can make standard function over columns
print(df[['one', 'two']].mean())
print('\n', df['one'].max())

one    1.5
two    2.5
dtype: float64

 3.0

# Литература